server.port=8082
server.error.include-stacktrace=always
server.error.include-message=always
spring.application.name=flashsale-order
spring.cloud.nacos.discovery.server-addr=${NACOS_ADDR:127.0.0.1:8848}

spring.datasource.url=${ORDER_DATASOURCE_URL:jdbc:postgresql://127.0.0.1:15432/flashsale_db}
spring.datasource.username=${ORDER_DATASOURCE_USERNAME:host}
spring.datasource.password=${ORDER_DATASOURCE_PASSWORD:hostpassword}
spring.datasource.driver-class-name=org.postgresql.Driver

mybatis.configuration.map-underscore-to-camel-case=true

spring.data.redis.host=${REDIS_HOST:127.0.0.1}
spring.data.redis.port=${REDIS_PORT:6379}
spring.data.redis.timeout=2000ms

spring.rabbitmq.host=${RABBITMQ_HOST:127.0.0.1}
spring.rabbitmq.port=${RABBITMQ_PORT:5672}
spring.rabbitmq.username=${RABBITMQ_USERNAME:guest}
spring.rabbitmq.password=${RABBITMQ_PASSWORD:guest}
spring.rabbitmq.listener.simple.acknowledge-mode=auto
spring.rabbitmq.listener.simple.prefetch=20

flashsale.seckill.stock-key-prefix=seckill:stock:
flashsale.seckill.bought-key-prefix=seckill:bought:
flashsale.seckill.result-key-prefix=seckill:result:
flashsale.seckill.result-ttl-seconds=300

jwt.secret=flashsale_phase_b_secret_key_please_change
jwt.expire-seconds=7200
internal.api.token=phase_c_internal_token

management.endpoints.web.exposure.include=health,info,prometheus
management.endpoint.health.show-details=always
logging.pattern.level=%5p [traceId:%X{traceId}]
