server.port=8082
server.error.include-stacktrace=always
server.error.include-message=always

spring.datasource.url=jdbc:postgresql://127.0.0.1:15432/flashsale_db
spring.datasource.username=host
spring.datasource.password=hostpassword
spring.datasource.driver-class-name=org.postgresql.Driver

mybatis.configuration.map-underscore-to-camel-case=true

spring.data.redis.host=127.0.0.1
spring.data.redis.port=6379
spring.data.redis.timeout=2000ms

spring.rabbitmq.host=127.0.0.1
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest
spring.rabbitmq.listener.simple.acknowledge-mode=auto
spring.rabbitmq.listener.simple.prefetch=20

flashsale.seckill.stock-key-prefix=seckill:stock:
flashsale.seckill.bought-key-prefix=seckill:bought:
flashsale.seckill.result-key-prefix=seckill:result:
flashsale.seckill.result-ttl-seconds=300

jwt.secret=flashsale_phase_b_secret_key_please_change
jwt.expire-seconds=7200
goods.internal.base-url=http://localhost:8081
internal.api.token=phase_c_internal_token

management.endpoints.web.exposure.include=health,info,prometheus
management.endpoint.health.show-details=always
logging.pattern.level=%5p [traceId:%X{traceId}]
