server.port=8081
server.error.include-stacktrace=always
server.error.include-message=always

spring.datasource.url=jdbc:postgresql://127.0.0.1:15432/flashsale_db
spring.datasource.username=host
spring.datasource.password=hostpassword
spring.datasource.driver-class-name=org.postgresql.Driver

mybatis.configuration.map-underscore-to-camel-case=true

jwt.secret=flashsale_phase_b_secret_key_please_change
jwt.expire-seconds=7200
internal.api.token=phase_c_internal_token
